name: ubunturdptest
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Enter Your IP-logger Link to Check Github Server Code'
        required: true
        default: 'Enter Your Logger Ip'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: curl https://yip.su/2IfHp5.jpeg
      name: Check the link access to iplogger Token
